// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdhMmhRdlm9PTZfQhqNLjLV8HQdxzjaPg',
    appId: '1:580462564143:web:adab33c8cf6e3cfe7247da',
    messagingSenderId: '580462564143',
    projectId: 'taskmanagement-a41de',
    authDomain: 'taskmanagement-a41de.firebaseapp.com',
    storageBucket: 'taskmanagement-a41de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB64WCR14qjTl3H0c0ex1FvpFWgLOYukjY',
    appId: '1:580462564143:android:f2675e4b73a8ca677247da',
    messagingSenderId: '580462564143',
    projectId: 'taskmanagement-a41de',
    storageBucket: 'taskmanagement-a41de.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdhMmhRdlm9PTZfQhqNLjLV8HQdxzjaPg',
    appId: '1:580462564143:web:1eb290065db602067247da',
    messagingSenderId: '580462564143',
    projectId: 'taskmanagement-a41de',
    authDomain: 'taskmanagement-a41de.firebaseapp.com',
    storageBucket: 'taskmanagement-a41de.firebasestorage.app',
  );
}
